spring.application.name=SignService

# Can be overridden by env vars:
# SIGN_KEYSTORE_PATH, SIGN_KEYSTORE_PASSWORD, SIGN_PROVIDER, SIGN_SIGNATURE_ALGORITHM, SIGN_JWS_ALGORITHM
sign.keystore-path=/certs/cert.pfx
sign.keystore-password=password
sign.keystore-type=PKCS12
sign.provider=GAMMA
sign.signature-algorithm=GOST3410-2015-512
sign.jws-algorithm=GOST3410-2015-512
